export const LOCAL_STORAGE_DATA_KEYNAME = 'zoyaUserData';

export const ATTEMPT_LOGIN = 'ATTEMPT_LOGIN';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const CREATE_USER = 'CREATE_USER';
export const SET_FORGET_PASSWORD = 'SET_FORGET_PASSWORD';
export const SET_FORGET_PASSWORD_VALIDATEPIN = 'SET_FORGET_PASSWORD_VALIDATEPIN';
export const SET_RESET_PASSWORD = 'SET_RESET_PASSWORD';

export const CREATE_DRIVER = 'CREATE_DRIVER';
export const CREATE_OWNER = 'CREATE_OWNER';
export const CREATE_PROMOCODE = 'CREATE_PROMOCODE';

export const ALL_USERS = 'ALL_USERS';
export const ALL_DRIVERS = 'ALL_DRIVERS';
export const ALL_OWNERS = 'ALL_OWNERS';
export const ALL_VEHICLES = 'ALL_VEHICLES';
export const ALL_PASSENGERS = 'ALL_PASSENGERS';
export const ALL_DISTRIBUTORS = 'ALL_DISTRIBUTORS';
export const ALL_ROLES = 'ALL_ROLES';
export const SEARCH_USERS = 'SEARCH_USERS';

export const SINGLE_VEHICLE = 'SINGLE_VEHICLE';

export const CREATE_VEHICLE = 'CREATE_VEHICLE';
export const VEHICLE_TYPES = 'VEHICLE_TYPES';
export const VEHICLE_CLASSES = 'VEHICLE_CLASSES';

export const PROMOCODES_BY_USERROLE = 'PROMOCODES_BY_USERROLE';
export const SEND_PROMOCODE_TO_ASSING_PAGE = 'SEND_PROMOCODE_TO_ASSING_PAGE';
export const ROLE_BASED_USERSBY_USERROLE = 'ROLE_BASED_USERSBY_USERROLE';
export const ASSIGN_PROMOCODE_TOUSERS = 'ASSIGN_PROMOCODE_TOUSERS';

export const GET_SINGLE_USER = 'GET_SINGLE_USER';
export const GET_SINGLE_USER_ROLES = 'GET_SINGLE_USER_ROLES';
export const GET_SINGLE_PROFILE = 'GET_SINGLE_PROFILE';
export const GET_SINGLE_ADDRESS = 'GET_SINGLE_ADDRESS';
export const GET_SINGLE_RESIDENCE_ADDRESS = 'GET_SINGLE_RESIDENCE_ADDRESS';
export const PUT_SINGLE_ADDRESS = 'PUT_SINGLE_ADDRESS';
export const POST_SINGLE_ADDRESS = 'POST_SINGLE_ADDRESS';
export const POST_SINGLE_PROFILE = 'POST_SINGLE_PROFILE';
export const POST_SINGLE_USER_PASSPORT_PICTURE = 'POST_SINGLE_USER_PASSPORT_PICTURE';
export const PUT_SINGLE_USER_PROFILE = 'PUT_SINGLE_USER_PROFILE';
export const POST_SINGLE_USER_PROFILE_PICTURE = 'POST_SINGLE_USER_PROFILE_PICTURE';
export const POST_SINGLE_USER_NID_PICTURE = 'POST_SINGLE_USER_NID_PICTURE';

export const UPLOAD_DOCUMENT = 'UPLOAD_DOCUMENT';
export const GET_DRIVER_BYUSERID = 'GET_DRIVER_BYUSERID';
export const MAP_DOCUMENTS_WITH_DRIVER = 'MAP_DOCUMENTS_WITH_DRIVER';
export const MAP_DOCUMENTS_WITH_VEHICLE = 'MAP_DOCUMENTS_WITH_VEHICLE';

export const ALL_DRIVER_TOCHOLON_EARNING_STATMENT = 'ALL_DRIVER_TOCHOLON_EARNING_STATMENT';
export const ALL_CHOLON_TODRIVER_EARNING_STATMENT = 'ALL_CHOLON_TODRIVER_EARNING_STATMENT';

export const POST_DRIVER_TRANSACTION_SETTLELMENT = 'POST_DRIVER_TRANSACTION_SETTLELMENT';

export const ALL_DRIVERS_WITH_DRIVERVEHICLE = 'ALL_DRIVERS_WITH_DRIVERVEHICLE';
export const MAP_DRIVER_WITH_VEHICLE = 'MAP_DRIVER_WITH_VEHICLE';

export const ALL_REGIONS = 'ALL_REGIONS';
export const FARES_BY_PICKUP_AND_DEST_REGIONID = 'FARES_BY_PICKUP_AND_DEST_REGIONID';

export const TRIP_TYPE = 'TRIP_TYPE';
export const TRIP_MODE = 'TRIP_MODE';

export const POST_FARE = 'POST_FARE';
export const PUT_FARE = 'PUT_FARE';

export const UPDATE_FARE_ROWS_BY_DISTRANGE_START_END = 'UPDATE_FARE_ROWS_BY_DISTRANGE_START_END';

export const CONFIGURABLE_PARAMS_DATA = 'CONFIGURABLE_PARAMS_DATA';

export const FETCH_REGION_TYPES = 'ACTION_FETCH_REGION_TYPES';
export const FETCH_REGION_TYPES_SUCCEEDED = 'ACTION_FETCH_REGION_TYPES_SUCCEEDED';
export const FETCH_REGION_TYPES_FAILED = 'ACTION_FETCH_REGION_TYPES_SUCCEEDED';

export const FETCH_REGIONS = 'ACTION_FETCH_REGIONS';
export const FETCH_REGIONS_SUCCEEDED = 'ACTION_FETCH_REGIONS_SUCCEEDED';
export const FETCH_REGIONS_FAILED = 'ACTION_FETCH_REGIONS_FAILED';

export const DELETE_REGION = 'ACTION_DELETE_REGION';
export const DELETE_REGION_SUCCEEDED = 'ACTION_DELETE_REGION_SUCCEEDED';
export const DELETE_REGION_FAILED = 'ACTION_DELETE_REGION_FAILED';

export const CREATE_REGION = 'ACTION_CREATE_REGION';
export const CREATE_REGION_SUCCEEDED = 'ACTION_CREATE_REGION_SUCCEEDED';
export const CREATE_REGION_FAILED = 'ACTION_CREATE_REGION_FAILED';

export const RESET_CREATE_REGION = 'ACTION_RESET_CREATE_REGION';

export const FETCH_REGION_DETAILS = 'ACTION_FETCH_REGION_DETAILS';
export const FETCH_REGION_DETAILS_SUCCEEDED = 'ACTION_FETCH_REGION_DETAILS_SUCCEEDED';
export const FETCH_REGION_DETAILS_FAILED = 'ACTION_FETCH_REGION_DETAILS_FAILED';

export const FETCH_REGION_POINTS = 'ACTION_FETCH_REGION_POINTS';
export const FETCH_REGION_POINTS_SUCCEEDED = 'ACTION_FETCH_REGION_POINTS_SUCCEEDED';
export const FETCH_REGION_POINTS_FAILED = 'ACTION_FETCH_REGION_POINTS_FAILED';

export const ADD_REGION_POINT = 'ACTION_ADD_REGION_POINT';
export const ADD_REGION_POINT_SUCCEEDED = 'ACTION_ADD_REGION_POINT_SUCCEEDED';
export const ADD_REGION_POINT_FAILED = 'ACTION_ADD_REGION_POINT_FAILED';

export const DELETE_REGION_POINT = 'ACTION_DELETE_REGION_POINT';
export const DELETE_REGION_POINT_SUCCEEDED = 'ACTION_DELETE_REGION_POINT_SUCCEEDED';
export const DELETE_REGION_POINT_FAILED = 'ACTION_DELETE_REGION_POINT_FAILED';

export const GET_TERMS = 'GET_TERMS';
export const SET_TERMS = 'SET_TERMS';

export const GET_PRIVACY = 'GET_PRIVACY';
export const SET_PRIVACY = 'SET_PRIVACY';

export const GET_SUPPORT = 'GET_SUPPORT';
export const SET_SUPPORT = 'SET_SUPPORT';

export const GET_MANUEL = 'GET_MANUEL';
export const SET_MANUEL = 'SET_MANUEL';

export const GET_FAQ = 'GET_FAQ';
export const SET_FAQ = 'SET_FAQ';

export const GET_ALL_ISSUES = 'GET_ALL_ISSUES';
export const GET_ALL_ISSUE_TAG = 'GET_ALL_ISSUE_TAG';
export const SET_ISSUE = 'SET_ISSUE';
export const SET_ISSUE_MESSAGE = 'SET_ISSUE_MESSAGE';
export const GET_USER_ALL_ISSUE_MESSAGE = 'GET_USER_ALL_ISSUE_MESSAGE';
export const SET_ISSUE_MESSAGE_REPLY = 'SET_ISSUE_MESSAGE_REPLY';
export const GET_SINGLE_ISSUES = 'GET_SINGLE_ISSUES';
export const SET_ISSUE_STATUS = 'SET_ISSUE_STATUS';

export const SET_ISSUE_MSG = 'SET_ISSUE_MSG';


export const GET_HELP_CONFIG = 'GET_HELP_CONFIG';


export const GET_ALL_NOTICES = 'GET_ALL_NOTICES';
export const GET_NOTICE_TYPE = 'GET_NOTICE_TYPE';
export const CREATE_NOTICE = 'CREATE_NOTICE';
export const GET_ALL_USERS = 'GET_ALL_USERS';
export const SEND_NOTICEINFO_TO_ASSING_PAGE = 'SEND_NOTICEINFO_TO_ASSING_PAGE';

export const GET_SINGLE_USER_TRACKER = 'GET_SINGLE_USER_TRACKER';
export const GET_SINGLE_TRACKER_POSITION = 'GET_SINGLE_TRACKER_POSITION';
export const GET_SINGLE_USER_TRACKER_LATEST_POSITION = 'GET_SINGLE_USER_TRACKER_LATEST_POSITION';
export const GET_SINGLE_USER_SINGLE_TRACKER_LATEST_POSITION = 'GET_SINGLE_USER_SINGLE_TRACKER_LATEST_POSITION';
export const GET_USER_ALL_TRACKERS_POSITION = 'GET_USER_ALL_TRACKERS_POSITION';

export const SET_TRACKER_CONFIGURATION = 'SET_TRACKER_CONFIGURATION';
export const PUT_TRACKER_CONFIGURATION = 'PUT_TRACKER_CONFIGURATION';

export const SET_TRACKER_AREA = 'SET_TRACKER_AREA';
export const GET_SINGLE_TARGET_TRACKER_AREAS = 'GET_SINGLE_TARGET_TRACKER_AREAS';
export const GET_SINGLE_TARGET_TRACKER_AREA = 'GET_SINGLE_TARGET_TRACKER_AREA';
export const UPDATE_SINGLE_TARGET_TRACKER_AREA = 'UPDATE_SINGLE_TARGET_TRACKER_AREA';
export const DELETE_SINGLE_TARGET_TRACKER_AREA = 'DELETE_SINGLE_TARGET_TRACKER_AREA';

export const GET_SINGLE_DANGER_TRACKER_AREAS = 'GET_SINGLE_DANGER_TRACKER_AREAS';
export const GET_SINGLE_DANGER_TRACKER_AREA = 'GET_SINGLE_DANGER_TRACKER_AREA';

export const SET_PHONE_NUMBER = 'SET_PHONE_NUMBER';
export const PATCH_PHONE_NUMBER = 'PATCH_PHONE_NUMBER';
export const DELETE_PHONE_NUMBER = 'DELETE_PHONE_NUMBER';
export const GET_SOS_NUMBER = 'GET_SOS_NUMBER';
export const SET_SOS_NUMBER = 'SET_SOS_NUMBER';
export const PATCH_SOS_NUMBER = 'PATCH_SOS_NUMBER';

export const SET_TRACKER_ACTIVE = 'SET_TRACKER_ACTIVE';
export const GET_ALL_TRACKER_HISTORY = 'GET_ALL_TRACKER_HISTORY';
export const GET_ALL_TRACKERS_HEALTH = 'GET_ALL_TRACKERS_HEALTH';
export const GET_ALL_TRACKER_REPORT = 'GET_ALL_TRACKER_REPORT';

export const GET_APP_CONFIG_DATA = 'GET_APP_CONFIG_DATA';
export const GET_NEAREST_POLICE_STATION_DATA = 'GET_NEAREST_POLICE_STATION_DATA';


export const GET_USER_SUBSCRIPTION = 'GET_USER_SUBSCRIPTION';
export const SET_USER_SUBSCRIPTION = 'SET_USER_SUBSCRIPTION';
export const SET_SUBSCRIPTION_INVOICE = 'SET_SUBSCRIPTION_INVOICE';
export const SET_SUBSCRIPTION_INVOICE_SSL = 'SET_SUBSCRIPTION_INVOICE_SSL';

export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_USER_PRODUCTS = 'GET_USER_PRODUCTS';

export const GET_SINGLE_USER_INVOICES = 'GET_SINGLE_USER_INVOICES';

export const GET_ALL_TRACKER_HEALTH = 'GET_ALL_TRACKER_HEALTH';
